import Image from 'next/image';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang='en' data-theme='nigth'>
      <body className='flex justify-center items-center px-4 md:px-0'>
        <Image src={'/assets/bg.jpg'} alt='background' fill={true} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
