import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang='en'>
      <body>
        <div className='overlay' />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
